server:
  port: 8080
mitmproxy:
  port: ${MITMPROXY_PORT:8088}
  path: ${MITMPROXY_PATH:/usr/bin/mitmproxy}
  store:
    active: false
    path: requests/
cache:
  expireSec: 300
  maxSize: 100
  cleanupPeriodSec: 10
